// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/report-cards/Classic.tsx": () => import("../components/mockups/report-cards/Classic.tsx"),
  "./components/mockups/report-cards/Elegant.tsx": () => import("../components/mockups/report-cards/Elegant.tsx"),
  "./components/mockups/report-cards/Modern.tsx": () => import("../components/mockups/report-cards/Modern.tsx")
};
